#pragma once

#define VIAL_KEYBOARD_UID {0x1F, 0xD1, 0xB1, 0xA2, 0xFC, 0x9B, 0xEF, 0xBF}


#define VIAL_UNLOCK_COMBO_ROWS {0,0}
#define VIAL_UNLOCK_COMBO_COLS {0,1}


#define DYNAMIC_KEYMAP_MACRO_COUNT 32
#define VIAL_COMBO_ENTRIES 32
#define VIAL_TAP_DANCE_ENTRIES 48
#define VIAL_KEY_OVERRIDE_ENTRIES 8